### ISSUE TITLE
Warning: Error in &&: invalid 'x' type in 'x && y'

### ISSUE THREAD

**Issue by Raghu-Akkihalli** [paulgovan/eAnalytics#2]
I am new to R and was trying out the eAnalytics demo by doing the following;

1. Installed R v3.4.2
2. Go to the R console and installed eAnalytics -> install.packages('eAnalytics')
3. load the library -> library('eAnalytics')
4. Try to launch the demo - eAnalytics::eAnalytics()
5. I see the following stacktrace;
Listening on http://127.0.0.1:7604
Warning: Error in &&: invalid 'x' type in 'x && y'
Stack trace (innermost first):
    61: shinydashboard::box
    60: tag
    59: tags$div
    58: div
    57: shiny::fluidRow
    56: tag
    55: tags$div
    54: div
    53: shinydashboard::tabItem
    52: lapply
    51: shinydashboard::tabItems
    50: tag
    49: tags$section
    48: tag
    47: tags$div
    46: div
    45: shinydashboard::dashboardBody
    44: inherits
    43: tagAssert
    42: shinydashboard::dashboardPage
     2: shiny::runApp
     1: eAnalytics::eAnalytics

What I am doing wrong?

Thank you!
Raghu

**Comment by paulgovan** [comment]
Hmm this one is puzzling to me. Would you make sure that you have the most recent version of the `shiny` package installed with `install.packages('shiny')`. Also, what OS are you using?

**Comment by xxhandup** [comment]
May I ask how you solved it? Just updated ergm's package? thank you

**Comment by paulgovan** [comment]
This issue was closed because I was unable to recreate the error.
